import 'package:flutter/services.dart';
import 'package:smart_storage_analyzer/core/constants/channel_constants.dart';
import 'package:smart_storage_analyzer/core/utils/logger.dart';

/// Service for sharing content from the app
class ShareService {
  static const platform = MethodChannel(ChannelConstants.mainChannel);

  /// Share text content
  static Future<bool> shareText(String text, {String? subject}) async {
    try {
      // For now, copy to clipboard as fallback
      // In production, this would use native sharing
      await Clipboard.setData(ClipboardData(text: text));

      Logger.info('Content copied to clipboard');

      // In a real implementation, this would call native share sheet
      // final result = await platform.invokeMethod('shareText', {
      //   'text': text,
      //   'subject': subject,
      // });

      return true;
    } catch (e) {
      Logger.error('Error sharing text', e);
      return false;
    }
  }

  /// Share files
  static Future<bool> shareFiles(List<String> filePaths, {String? text}) async {
    try {
      // In a real implementation, this would share files via native platform
      // final result = await platform.invokeMethod('shareFiles', {
      //   'paths': filePaths,
      //   'text': text,
      // });

      // For now, just log
      Logger.info('Sharing ${filePaths.length} files');

      return true;
    } catch (e) {
      Logger.error('Error sharing files', e);
      return false;
    }
  }

  /// Generate share text for a category
  static String generateCategoryShareText({
    required String categoryName,
    required String size,
    required int fileCount,
  }) {
    return '''
📁 $categoryName Storage Report
📊 Size: $size
📎 Files: $fileCount

Generated by Smart Storage Analyzer
''';
  }

  /// Generate share text for multiple categories
  static String generateMultipleCategoriesShareText(
    List<Map<String, dynamic>> categories,
  ) {
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('📊 Storage Report');
    buffer.writeln('Generated: ${DateTime.now().toString().split('.')[0]}');
    buffer.writeln('');

    int totalSize = 0;
    int totalFiles = 0;

    for (final category in categories) {
      final size = category['size'] as int;
      final files = category['files'] as int;
      final name = category['name'] as String;

      totalSize += size;
      totalFiles += files;

      buffer.writeln('📁 $name');
      buffer.writeln('   Size: ${_formatBytes(size)}');
      buffer.writeln('   Files: $files');
      buffer.writeln('');
    }

    buffer.writeln('📈 Total Summary');
    buffer.writeln('   Total Storage: ${_formatBytes(totalSize)}');
    buffer.writeln('   Total Files: $totalFiles');
    buffer.writeln('');
    buffer.writeln('Generated by Smart Storage Analyzer');

    return buffer.toString();
  }

  /// Format bytes to human readable string
  static String _formatBytes(int bytes) {
    if (bytes <= 0) return '0 B';

    const units = ['B', 'KB', 'MB', 'GB', 'TB'];
    int digitGroups = (bytes.toDouble().toString().length / 3).floor();
    if (digitGroups >= units.length) digitGroups = units.length - 1;

    final size = bytes / (1024.0 * digitGroups);
    return '${size.toStringAsFixed(2)} ${units[digitGroups]}';
  }

  /// Generate share text for a single file
  static String generateFileShareText({
    required String fileName,
    required String size,
    required String path,
  }) {
    final buffer = StringBuffer();
    buffer.writeln('📄 File Details');
    buffer.writeln('─' * 30);
    buffer.writeln('Name: $fileName');
    buffer.writeln('Size: $size');
    buffer.writeln('Path: $path');
    buffer.writeln();
    buffer.writeln('Shared via Smart Storage Analyzer');

    return buffer.toString();
  }

  /// Generate share text for multiple files
  static String generateMultipleFilesShareText(
    List<Map<String, dynamic>> files,
  ) {
    final buffer = StringBuffer();
    buffer.writeln('📄 Files Report');
    buffer.writeln('━' * 40);
    buffer.writeln();
    buffer.writeln('Total Files: ${files.length}');

    int totalSize = 0;
    for (final file in files) {
      if (file['size'] is int) {
        totalSize += file['size'] as int;
      }
    }

    buffer.writeln('Total Size: ${_formatBytes(totalSize)}');
    buffer.writeln();
    buffer.writeln('File List:');
    buffer.writeln('─' * 40);

    for (int i = 0; i < files.length; i++) {
      final file = files[i];
      buffer.writeln();
      buffer.writeln('${i + 1}. ${file['name']}');
      buffer.writeln('   Size: ${_formatBytes(file['size'] as int)}');
      if (file['path'] != null) {
        buffer.writeln('   Path: ${file['path']}');
      }
    }

    buffer.writeln();
    buffer.writeln('─' * 40);
    buffer.writeln('Shared via Smart Storage Analyzer');
    buffer.writeln('Generated on ${DateTime.now().toString().split('.')[0]}');

    return buffer.toString();
  }
}
